source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '4.2.4'
gem 'pg'
gem 'jbuilder', '~> 2.0'
gem 'jsonapi-resources'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'database_cleaner'
end

group :development, :test do
  gem 'byebug'
  gem 'fuubar'
  gem 'rspec-rails', '~> 3.0'
  gem 'pry-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers', '~> 2.8.0', require: false
  gem 'launchy', require: false
  gem 'valid_attribute'
end

group :production, :staging do
  gem 'rails_12factor'
end
